(() => {
  'use strict';
  const $ = selector => document.querySelector(selector);
  const STORAGE = 'firstmate-tracker:pairing:v1';
  const PAST = new Set(['done', 'paused', 'expired']);
  const LABELS = { in_progress: 'In progress', review: 'Needs review', done: 'Done', paused: 'Paused', expired: 'Expired', blocked: 'Blocked', unknown: 'Unverified', pending: 'Open' };
  const views = { projects: ['Your projects', 'The latest handoff, and what comes next.'], activity: ['Recent activity', 'Complete saved messages from the latest seven days.'], decisions: ['Decisions and tests', 'The work that needs your review, direction or a hands-on check.'], history: ['History', 'Completed and paused work, and all saved chat updates.'] };
  let pairing = null, snapshot = null, busy = false, connection = 'unpaired', errorText = '', discovered = '', discoveryProof = '', generation = 0, displayLimit = 12, imageTrigger = null;
  let lastFetched = null, refreshTimer = null, searchTimer = null, loadId = 0, endpointProof = null, proofPromise = null;
  const objectUrls = new Set(), controllers = new Set(), assetControllers = new Set(), feedbackDrafts = new Map();

  function el(tag, cls, text) { const node = document.createElement(tag); if (cls) node.className = cls; if (text !== undefined && text !== null) node.textContent = String(text); return node; }
  function button(text, action, cls = 'button') { const node = el('button', cls, text); node.type = 'button'; node.addEventListener('click', action); return node; }
  function time(value, year = false) { const d = new Date(value); if (!value || Number.isNaN(d.getTime())) return 'Time not recorded'; return new Intl.DateTimeFormat('en-GB', { timeZone: 'Europe/London', day: 'numeric', month: 'short', ...(year ? { year: 'numeric' } : {}), hour: '2-digit', minute: '2-digit' }).format(d); }
  function messageTime(u) { return u.message_created_at || u.message_completed_at || u.first_observed_at || u.last_observed_at; }
  function score(value) { return Date.parse(value) || 0; }
  function pill(text, tone = '') { return el('span', `pill ${tone}`, text); }
  function workPill(state) { return pill(LABELS[state] || state || 'Unverified', state === 'review' ? 'review' : ['blocked', 'unknown'].includes(state) ? 'warning' : state === 'done' ? 'success' : ''); }
  function executePill(state) { return pill(`Agent: ${{ active: 'recorded running', inactive: 'recorded idle', unknown: 'unverified' }[state] || 'unverified'}`, state === 'active' ? 'success' : state === 'unknown' ? 'warning' : ''); }
  function empty(title, text) { const node = el('section', 'empty'); node.append(el('h2', '', title), el('p', '', text)); return node; }
  function route() { const [page = 'projects', query = ''] = location.hash.slice(1).split('?'); const p = new URLSearchParams(query); return { view: Object.hasOwn(views, page) ? page : page === 'project' || page === 'update' || page === 'task' ? page : 'projects', id: p.get('id') || '', thread: p.get('thread') || '' }; }
  function routeHref(view, id, thread) { const p = new URLSearchParams(); if (id) p.set('id', id); if (thread) p.set('thread', thread); return `#${view}${p.size ? `?${p}` : ''}`; }
  function routeLink(text, view, id, thread, cls = 'text-action') { const node = el('a', cls, text); node.href = routeHref(view, id, thread); return node; }
  function classifyReference(raw) {
    if (typeof raw !== 'string' || !raw.trim() || /[\u0000-\u001f]/.test(raw)) return { kind: 'unavailable' };
    const value = raw.trim();
    if (/^[a-z]:[\\/]/i.test(value) || /^\\\\/.test(value) || /^\//.test(value)) return { kind: 'laptop', value, file: true };
    try {
      const url = new URL(value); if (url.username || url.password) return { kind: 'unavailable' };
      if (url.protocol === 'file:') return { kind: 'laptop', value, file: true };
      if (url.protocol === 'codex:') return { kind: 'codex', value: url.href, openable: ['threads', 'review'].includes(url.hostname) };
      if (!['http:', 'https:'].includes(url.protocol)) return { kind: 'unavailable' };
      const host = url.hostname.toLowerCase().replace(/\.$/, ''), ipv6 = host.replace(/^\[|\]$/g, ''), parts = /^\d+\.\d+\.\d+\.\d+$/.test(host) ? host.split('.').map(Number) : null;
      const privateIp = parts && (parts[0] === 0 || parts[0] === 10 || parts[0] === 127 || parts[0] === 169 && parts[1] === 254 || parts[0] === 192 && parts[1] === 168 || parts[0] === 172 && parts[1] >= 16 && parts[1] <= 31 || parts[0] === 100 && parts[1] >= 64 && parts[1] <= 127);
      const privateHost = host === 'localhost' || /\.(localhost|local|lan|internal)$/.test(host) || !host.includes('.') && !host.includes(':') || ipv6 === '::' || ipv6 === '::1' || /^(fc|fd|fe[89ab])/.test(ipv6) && ipv6.includes(':') || ipv6.startsWith('::ffff:');
      return { kind: privateIp || privateHost ? 'laptop' : 'web', value: url.href, file: false };
    } catch { return { kind: 'unavailable' }; }
  }
  function copyReference(raw, label) {
    const wrap = el('span', 'reference-copy'), status = el('span', 'copy-status'); status.setAttribute('role', 'status');
    wrap.append(button(label, async () => { try { await navigator.clipboard.writeText(raw); status.textContent = 'Copied. Use this on your laptop.'; } catch { let field = wrap.querySelector('textarea'); if (!field) { field = el('textarea', 'copy-reference-value'); field.readOnly = true; field.setAttribute('aria-label', 'Laptop reference to copy'); wrap.append(field); } field.value = raw; field.focus(); field.select(); status.textContent = 'Select and copy this reference, then use it on your laptop.'; } }, 'button subtle'), status); return wrap;
  }
  function externalLink(text, raw, cls = 'text-action') {
    const ref = classifyReference(raw); if (ref.kind === 'unavailable') return null;
    if (ref.kind === 'web') { const node = el('a', cls, text); node.href = ref.value; node.rel = 'noopener noreferrer'; node.target = '_blank'; return node; }
    const wrap = el('span', 'reference-link');
    if (ref.kind === 'codex') { const link = el(ref.openable ? 'a' : 'span', cls, text); if (ref.openable) link.href = ref.value; link.setAttribute('aria-label', `${text} (needs Codex desktop)`); wrap.append(link, el('span', 'reference-note', 'Needs Codex desktop'), copyReference(ref.value, 'Copy chat link')); }
    else { wrap.append(el('span', cls, text), el('span', 'reference-note', 'Laptop only')); if (text !== raw) wrap.append(el('code', 'reference-address', ref.value)); wrap.append(copyReference(raw, ref.file ? 'Copy file path' : 'Copy laptop link')); }
    return wrap;
  }
  function validateEndpoint(raw) { let url; try { url = new URL(raw); } catch { throw new Error('Enter the complete HTTPS connection address from the Windows tracker, or leave it blank for the automatic connection.'); } if (url.username || url.password || url.search || url.hash || url.port || !['', '/'].includes(url.pathname)) throw new Error('Use only the laptop connection address, without a path, port, key or query string.'); if (url.protocol !== 'https:' || !url.hostname.endsWith('.trycloudflare.com')) throw new Error('Use the current HTTPS tunnel address from Firstmate Project Tracker in Windows. This gateway cannot verify localhost or other connection types.'); return url.origin; }
  function artifactPath(raw) { if (typeof raw !== 'string') return ''; let path = raw; try { if (/^[a-z]+:/i.test(raw)) { const url = new URL(raw); if (url.username || url.password || url.search || url.hash) return ''; const loopback = ['localhost', '127.0.0.1', '[::1]'].includes(url.hostname); if (!loopback && url.origin !== pairing?.endpoint) return ''; path = url.pathname; } } catch { return ''; } path = path.replace(/^\/?/, '/'); return /^\/update-assets\/[a-f0-9]{64}(?:\.[a-z0-9]+){1,3}$/i.test(path) ? path : ''; }
  function safeName(raw) { return String(raw || 'project-artifact').replace(/[\\/\u0000-\u001f<>:"|?*]/g, '_').slice(0, 180) || 'project-artifact'; }
  function revokeAssets() { generation += 1; assetControllers.forEach(c => c.abort()); assetControllers.clear(); objectUrls.forEach(url => URL.revokeObjectURL(url)); objectUrls.clear(); if ($('#imageViewer').open) $('#imageViewer').close(); $('#viewerImage').removeAttribute('src'); }
  function forget() { loadId += 1; busy = false; endpointProof = null; proofPromise = null; feedbackDrafts.clear(); controllers.forEach(c => c.abort()); revokeAssets(); pairing = null; snapshot = null; lastFetched = null; connection = 'unpaired'; errorText = ''; try { sessionStorage.removeItem(STORAGE); } catch {} $('#pairingKey').value = ''; $('#pairingKey').type = 'password'; $('#showKey').textContent = 'Show'; $('#showKey').setAttribute('aria-pressed', 'false'); $('#endpoint').value = ''; $('#pairError').hidden = true; render(); }
  function denyPairing() { forget(); connection = 'denied'; errorText = 'Pairing was refused. Check the key in Firstmate Project Tracker in Windows, then connect again.'; $('#pairError').textContent = errorText; $('#pairError').hidden = false; openConnection(); render(); }
  function savePairing() { try { if (pairing && $('#rememberTab').checked) sessionStorage.setItem(STORAGE, JSON.stringify(pairing)); else sessionStorage.removeItem(STORAGE); } catch {} }
  function remember() { try { const raw = JSON.parse(sessionStorage.getItem(STORAGE)); if (raw && typeof raw.key === 'string' && raw.key.length >= 16 && raw.key.length <= 512) pairing = { endpoint: validateEndpoint(raw.endpoint), key: raw.key, manual: raw.manual === true }; } catch { try { sessionStorage.removeItem(STORAGE); } catch {} } }

  async function discover() {
    try {
      const response = await fetch(`./connection.json?check=${Date.now()}`, { cache: 'no-store', credentials: 'omit', referrerPolicy: 'no-referrer' });
      if (!response.ok) throw new Error('discovery_failed'); const body = await response.json();
      if (body.schema_version !== 1 || typeof body.endpoint !== 'string' || !body.endpoint) throw new Error('no_endpoint');
      const endpoint = validateEndpoint(body.endpoint), host = new URL(endpoint).hostname;
      if (!host.endsWith('.trycloudflare.com') || host === 'trycloudflare.com') throw new Error('invalid_discovery_host');
      discovered = endpoint; discoveryProof = /^[a-f0-9]{64}$/i.test(body.proof || '') ? body.proof : ''; $('#discoveryStatus').textContent = 'Laptop connection found. Enter your pairing key to verify the address and read your projects.';
      return endpoint;
    } catch { discovered = ''; discoveryProof = ''; $('#discoveryStatus').textContent = 'The automatic laptop connection is unavailable. Start Firstmate Project Tracker in Windows, or enter a private HTTPS address below.'; return ''; }
  }
  async function verifyDiscovered(key, endpoint, proof) {
    if (!endpoint || !proof || !globalThis.crypto?.subtle) return false;
    try { const bytes = new TextEncoder(), signature = Uint8Array.from(proof.match(/.{2}/g), hex => parseInt(hex, 16)), imported = await crypto.subtle.importKey('raw', bytes.encode(key), { name: 'HMAC', hash: 'SHA-256' }, false, ['verify']); return await crypto.subtle.verify('HMAC', imported, signature, bytes.encode(`Firstmate endpoint v1\n${endpoint}`)); } catch { return false; }
  }
  async function challengeEndpoint(expected) {
    if (expected !== pairing || !globalThis.crypto?.subtle) throw new Error('proof');
    if (endpointProof?.pairing === expected && endpointProof.endpoint === expected.endpoint && performance.now() - endpointProof.at < 25000) return;
    if (proofPromise?.pairing === expected && proofPromise.endpoint === expected.endpoint) return proofPromise.promise;
    const endpoint = expected.endpoint;
    const promise = (async () => {
      const ctrl = new AbortController(); controllers.add(ctrl); const deadline = setTimeout(() => ctrl.abort(), 10000);
      try {
        const nonce = Array.from(crypto.getRandomValues(new Uint8Array(32)), value => value.toString(16).padStart(2, '0')).join('');
        const response = await fetch(endpoint + '/api/pairing/proof', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nonce, endpoint }), cache: 'no-store', credentials: 'omit', redirect: 'error', referrerPolicy: 'no-referrer', signal: ctrl.signal });
        if (!response.ok) throw new Error('proof'); const raw = await response.text(); if (raw.length > 2048) throw new Error('proof'); const body = JSON.parse(raw);
        if (body.nonce !== nonce || body.endpoint !== endpoint || body.service !== 'Firstmate Project Tracker private gateway' || body.version !== 1 || !/^[a-f0-9]{64}$/.test(body.proof || '')) throw new Error('proof');
        const bytes = new TextEncoder(), signature = Uint8Array.from(body.proof.match(/.{2}/g), hex => parseInt(hex, 16)), key = await crypto.subtle.importKey('raw', bytes.encode(expected.key), { name: 'HMAC', hash: 'SHA-256' }, false, ['verify']);
        if (!await crypto.subtle.verify('HMAC', key, signature, bytes.encode(`Firstmate challenge v1\n${nonce}\n${endpoint}`)) || expected !== pairing || endpoint !== expected.endpoint) throw new Error('proof');
        endpointProof = { pairing: expected, endpoint, at: performance.now() };
      } catch { throw new Error('proof'); } finally { clearTimeout(deadline); controllers.delete(ctrl); }
    })();
    proofPromise = { pairing: expected, endpoint, promise };
    try { await promise; } finally { if (proofPromise?.promise === promise) proofPromise = null; }
  }
  async function request(path, asBlob = false, expected = pairing) {
    if (!expected || expected !== pairing) throw new Error('pairing_changed');
    const endpoint = expected.endpoint; await challengeEndpoint(expected); if (expected !== pairing || endpoint !== expected.endpoint) throw new Error('pairing_changed');
    const ctrl = new AbortController(); controllers.add(ctrl); if (asBlob) assetControllers.add(ctrl); const deadline = setTimeout(() => ctrl.abort(), asBlob ? 30000 : 15000);
    try {
      const response = await fetch(endpoint + path, { headers: { Authorization: `Bearer ${expected.key}` }, cache: 'no-store', credentials: 'omit', redirect: 'error', referrerPolicy: 'no-referrer', signal: ctrl.signal });
      if (!response.ok) { const error = new Error(response.status === 401 || response.status === 403 ? 'auth' : response.status === 429 ? 'rate' : response.status === 503 ? 'upstream' : 'response'); error.status = response.status; if (error.message === 'auth' && expected === pairing) denyPairing(); throw error; }
      if (expected !== pairing) throw new Error('pairing_changed'); return asBlob ? response.blob() : response.json();
    } finally { clearTimeout(deadline); controllers.delete(ctrl); assetControllers.delete(ctrl); }
  }
  async function load({ rediscover = true } = {}) {
    if (!pairing || busy) return; const currentLoad = ++loadId, startingPairing = pairing; busy = true; connection = 'loading'; endpointProof = null; renderConnection(); if (!snapshot) render();
    if (!pairing.manual) {
      const automaticEndpoint = rediscover ? await discover() : discovered;
      if (currentLoad !== loadId || startingPairing !== pairing) return;
      if (!automaticEndpoint) { busy = false; connection = 'offline'; errorText = 'The laptop connection address is unavailable. Your laptop or this device may be offline, asleep or reconnecting. Start Firstmate Project Tracker in Windows, reconnect to the internet, then refresh. ' + (snapshot ? 'Your pairing and saved snapshot are retained.' : 'Your pairing is retained.') + ' No pairing key was sent.'; render(); return; }
      const expectedPairing = pairing, verifiedEndpoint = discovered, verifiedProof = discoveryProof;
      if (!await verifyDiscovered(expectedPairing.key, verifiedEndpoint, verifiedProof)) { if (currentLoad !== loadId || expectedPairing !== pairing) return; busy = false; connection = 'offline'; errorText = 'The laptop address could not be verified with this pairing key. Start the tracker in Windows and copy its current key, then connect again. No key was sent to the unverified address.'; render(); return; }
      if (currentLoad !== loadId || expectedPairing !== pairing) return; pairing.endpoint = verifiedEndpoint; savePairing();
    }
    const expected = pairing;
    const results = await Promise.allSettled(['/api/projects', '/api/updates', '/api/briefs', '/api/sync/status'].map(path => request(path, false, expected)));
    if (currentLoad !== loadId || expected !== pairing) return; busy = false;
    const denied = results.some(r => r.status === 'rejected' && r.reason.message === 'auth');
    if (denied) { forget(); connection = 'denied'; errorText = 'Pairing was refused. Check the key in Firstmate Project Tracker in Windows, then connect again.'; $('#pairError').textContent = errorText; $('#pairError').hidden = false; openConnection(); render(); return; }
    if (results[0].status === 'fulfilled' && results[1].status === 'fulfilled' && Array.isArray(results[0].value.tasks) && Array.isArray(results[1].value.updates) && Array.isArray(results[1].value.sources)) {
      const firstSnapshot = !snapshot; snapshot = { projects: results[0].value, feed: results[1].value, briefs: results[2].status === 'fulfilled' && Array.isArray(results[2].value.briefs) ? results[2].value : { briefs: [], unavailable: true }, sync: results[3].status === 'fulfilled' ? results[3].value : null };
      connection = 'online'; errorText = ''; lastFetched = new Date().toISOString(); $('#connectionPanel').hidden = true; $('#pairingKey').value = ''; $('#pairError').hidden = true; render(); if (firstSnapshot && route().view === 'update') requestAnimationFrame(focusRoute);
    } else {
      const kinds = results.filter(r => r.status === 'rejected').map(r => r.reason.message);
      connection = 'offline'; errorText = kinds.includes('proof') ? 'The current laptop connection could not prove its identity. The laptop may be asleep, restarting or using a newer address. Start the tracker in Windows and refresh. No pairing key was sent to the unverified connection.' : kinds.includes('rate') ? 'Too many pairing attempts. Wait a minute, then refresh.' : kinds.includes('upstream') ? 'The laptop connection is online, but its saved-data service is unavailable. Restart Firstmate Project Tracker in Windows.' : 'The laptop could not be reached. It may be asleep, offline or restarting. Start the tracker in Windows, then refresh. The HTTPS connection can take a moment to update.';
      render();
    }
  }
  async function connect(event) {
    event.preventDefault(); if (busy) return; $('#pairError').hidden = true;
    try {
      const raw = $('#endpoint').value.trim(); const endpoint = raw || await discover(); if (!endpoint) throw new Error('No laptop address is available yet. Start Firstmate Project Tracker in Windows and try again.');
      const key = $('#pairingKey').value.trim(); if (!key || key.length < 16 || key.length > 512 || /[\r\n\u0000]/.test(key)) throw new Error('Paste the complete pairing key from Firstmate Project Tracker in Windows.');
      revokeAssets(); snapshot = null; lastFetched = null; pairing = { endpoint: validateEndpoint(endpoint), key, manual: Boolean(raw) }; savePairing(); await load({ rediscover: false });
    } catch (error) { $('#pairError').textContent = error.message; $('#pairError').hidden = false; }
  }
  function openConnection() { $('#connectionPanel').hidden = false; $('#pairingKey').value = ''; $('#endpoint').value = pairing?.manual ? pairing.endpoint : ''; $('#forgetButton').hidden = !pairing; $('#connectionTitle').scrollIntoView({ block: 'start', behavior: 'auto' }); $('#pairingKey').focus({ preventScroll: true }); }
  function renderConnection() {
    $('#connectionLabel').textContent = { unpaired: 'Laptop not paired', denied: 'Pairing refused', loading: 'Connecting to laptop…', online: 'Laptop connected', offline: 'Laptop unavailable' }[connection];
    $('#connectionDot').className = `status-dot ${connection === 'online' ? 'online' : connection === 'offline' || connection === 'denied' ? 'offline' : ''}`;
    $('#refreshButton').hidden = !pairing; $('#refreshButton').disabled = busy; $('#refreshButton').textContent = busy ? 'Refreshing…' : 'Refresh'; $('#connectionButton').textContent = pairing ? 'Connection' : 'Connect laptop'; $('#connectSubmit').disabled = busy; $('#connectSubmit').textContent = busy ? 'Connecting…' : 'Connect'; $('#forgetButton').hidden = !pairing;
  }
  function renderNotice() {
    const node = $('#notice'); node.replaceChildren(); node.hidden = true;
    if (connection === 'offline' || connection === 'denied') { node.hidden = false; node.append(el('strong', '', connection === 'denied' ? 'Pairing needs attention' : 'Laptop unavailable'), el('p', '', errorText)); if (snapshot) node.append(el('p', '', `Showing the in-memory snapshot fetched ${time(lastFetched, true)}. It will not update until the laptop reconnects.`)); return; }
    if (!snapshot) return;
    const sync = snapshot.sync, sources = sync?.sources || [], newest = sync?.last_success_at || sources.reduce((latest, s) => score(s.last_success_at) > score(latest) ? s.last_success_at : latest, '');
    if (!sync || !newest || Date.now() - score(newest) > 10 * 60 * 1000 || sources.some(s => s.availability === 'unavailable')) {
      node.hidden = false; node.append(el('strong', '', 'Some source checks need attention'), el('p', '', newest ? `Last successful reader check ${time(newest, true)}. Individual source dates and archive limits appear with the messages.` : 'The reader has no successful source-check time available. Saved messages remain readable; their dates do not prove the current state of the work.'));
    }
  }
  function welcome() {
    const node = el('section', 'welcome'); node.append(el('h2', '', 'Your work stays on your laptop.'), el('p', '', 'Pair this tab to read project summaries, decisions and complete saved assistant updates. This public page contains the application only.'), button('Connect laptop', openConnection, 'button primary'));
    const steps = el('ol', 'pairing-steps');
    for (const [title, detail] of [['Start the laptop tracker.', 'Find Firstmate Project Tracker in the Windows Start menu. Keep the laptop awake while you read.'], ['Copy the pairing key.', 'Use the Windows control to copy the key, then paste it into this tab.'], ['Read from your phone.', 'The page finds the current HTTPS connection. If the laptop sleeps or the connection changes, refresh when it is back online.']]) { const li = el('li'); const text = el('span'); text.append(el('strong', '', title + ' '), document.createTextNode(detail)); li.append(text); steps.append(li); }
    node.append(steps, el('p', 'privacy-note', 'Pairing is private to this tab. Project records are kept in memory only, and are cleared when you forget pairing.')); return node;
  }
  function matches(text) { return !$('#search').value.trim() || String(text).toLowerCase().includes($('#search').value.trim().toLowerCase()); }
  function projectMatches(name) { return !$('#projectFilter').value || name === $('#projectFilter').value; }
  function sourceFor(id) { return snapshot.feed.sources.find(s => s.thread_id === id); }
  function taskThread(task) { return task.thread_id || task.chat_url?.match(/threads\/([^/?#]+)/)?.[1]; }
  function briefFor(task, projectName) { const newest = items => [...items].sort((a, b) => score(b.authored_at) - score(a.authored_at))[0]; if (task) { const exact = snapshot.briefs.briefs.filter(b => b.task_id === task.task_id); return newest(exact) || newest(snapshot.briefs.briefs.filter(b => (b.thread_id || b.source_id) === taskThread(task))); } return newest(snapshot.briefs.briefs.filter(b => snapshot.projects.tasks.some(t => !PAST.has(t.work_state) && t.project_name === projectName && (b.task_id === t.task_id || (b.thread_id || b.source_id) === taskThread(t))))); }
  function briefStale(brief) { const updates = snapshot.feed.updates.filter(u => u.thread_id === (brief.thread_id || brief.source_id)); const ref = updates.find(u => u.id === brief.source_update_id); return updates.some(u => score(messageTime(u)) > score(brief.evidence_through || brief.authored_at)) || (Number.isInteger(brief.source_revision_count) && ref && ref.revision_count !== brief.source_revision_count); }
  function briefFreshness(brief) { const node = el('p', `freshness ${briefStale(brief) ? 'warning' : ''}`); node.append(document.createTextNode(briefStale(brief) ? 'Newer saved messages or a revised source make this summary due for review. ' : ''), document.createTextNode(`Evidence through ${time(brief.evidence_through || brief.authored_at, true)}. Summary written ${time(brief.authored_at, true)}.`)); return node; }
  function projectsView() {
    const list = el('div', 'project-list'); const groups = snapshot.projects.active || [];
    groups.filter(g => projectMatches(g.name) && matches([g.name, g.summary, g.status, ...g.tasks.map(t => t.title)].join(' '))).forEach(group => {
      const card = el('article', 'project-card'), copy = el('div'), heading = el('h2'), brief = briefFor(null, group.name); heading.append(routeLink(group.name, 'project', group.id, '', '')); copy.append(heading, el('p', '', brief?.bottomline || group.summary || group.status || 'No summary recorded.'));
      const next = el('p', 'next-line'); next.append(el('strong', '', 'Next: '), document.createTextNode(brief?.recommended_next || group.next_action || 'No next action recorded.')); copy.append(next);
      const pills = el('div', 'status-pills'); const review = group.tasks.filter(t => t.work_state === 'review').length; pills.append(pill(`${group.tasks.length} current ${group.tasks.length === 1 ? 'task' : 'tasks'}`)); if (review) pills.append(pill(`${review} needs review`, 'review')); if (brief && briefStale(brief)) pills.append(pill('Summary due for review', 'warning'));
      const foot = el('div', 'card-foot'); const through = brief?.evidence_through || group.summary_source_time || group.tasks.reduce((latest, t) => score(t.source_time) > score(latest) ? t.source_time : latest, ''); foot.append(el('span', 'small', `Evidence: ${time(through, true)}`), routeLink('Read summary and updates', 'project', group.id)); card.append(copy, pills, foot); list.append(card);
    });
    if (!list.childNodes.length) list.append(empty('No current projects match', 'Try another project or clear your search. Completed and paused work stays in History.'));
    const other = (snapshot.projects.all_projects || []).filter(g => !groups.some(a => a.name === g.name || a.id === g.id) && projectMatches(g.name) && matches(g.name));
    if (other.length) { const intro = el('div', 'section-intro'); intro.append(el('h2', '', 'Project directory'), el('p', '', 'Saved project spaces with no current handoff.')); list.append(intro); other.forEach(g => { const row = el('div', 'task-row'); const heading = el('h3'); heading.append(routeLink(g.name, 'project', g.id, '', '')); row.append(heading, el('p', '', g.status || 'No current handoff recorded.')); list.append(row); }); }
    return list;
  }
  function appendParagraph(host, heading, text) { if (!text) return; host.append(el('h3', '', heading), el('p', '', text)); }
  function feedback(host, title, action = {}) {
    const section = el('section', 'feedback'); section.append(el('h3', '', 'Your feedback'));
    const draftKey = host.dataset.briefId || host.dataset.taskId || title, draft = feedbackDrafts.get(draftKey) || { text: '', selected: '' }; let selected = draft.selected;
    if (Array.isArray(action.options)) action.options.forEach((option, i) => { const label = el('label', 'decision-choice'), radio = el('input'), choice = option.label || option.title || option.value || `Choice ${i + 1}`; radio.type = 'radio'; radio.name = `choice-${draftKey}`; radio.checked = selected === choice; radio.addEventListener('change', () => { selected = choice; feedbackDrafts.set(draftKey, { text: input.value, selected }); }); const copy = el('span', '', choice); if (option.description) copy.append(el('small', '', ` ${option.description}`)); label.append(radio, copy); section.append(label); });
    const id = `feedback-${Math.random().toString(36).slice(2)}`, label = el('label', 'feedback-label', 'What did you find, or what should happen next?'); label.htmlFor = id; const input = el('textarea'); input.id = id; input.value = draft.text; input.addEventListener('input', () => feedbackDrafts.set(draftKey, { text: input.value, selected })); input.placeholder = 'Add your feedback or direction'; const status = el('p', 'copy-status'); status.setAttribute('role', 'status'); const controls = el('div', 'button-wrap'); controls.append(button('Copy feedback', async () => { const text = `For ${title}:\n${selected ? `My choice: ${selected}\n` : ''}\n${input.value || action.feedback_template || 'My feedback:'}`; try { await navigator.clipboard.writeText(text); status.textContent = 'Copied. Paste this into your coordinator chat.'; } catch { input.value = text; feedbackDrafts.set(draftKey, { text, selected }); input.focus(); input.select(); status.textContent = 'Select and copy the text, then paste it into your coordinator chat.'; } })); const chat = externalLink('Open coordinator', snapshot.projects.coordinator_url); if (chat) controls.append(chat); section.append(label, input, controls, status, el('p', 'small', 'Feedback stays here until you copy it. This reader does not send instructions to agents.')); host.append(section);
  }
  function briefView(brief, withFeedback = true) {
    const node = el('section', 'brief'); node.dataset.briefId = brief.id; node.append(el('p', 'brief-label', 'Coordinator summary · separate from the original chat'), el('p', 'bottomline', brief.bottomline || 'No summary text recorded.'));
    if (brief.stage?.label) node.append(pill(brief.stage.label)); if (brief.stage?.detail) node.append(el('p', '', brief.stage.detail));
    appendParagraph(node, 'What changed', brief.what_changed); appendParagraph(node, 'What this means', brief.what_it_means);
    if (brief.comparison?.versions?.length) { const comparison = brief.comparison; node.append(el('h3', '', comparison.title || 'Compare the versions')); if (comparison.instruction) node.append(el('p', '', comparison.instruction)); comparison.versions.forEach(version => { node.append(el('h4', '', version.label || version.title || 'Version'), el('p', '', version.text || version.prose || '')); }); if (comparison.reveal) { const reveal = el('details', 'source-details'); reveal.append(el('summary', '', 'Reveal original and checker results')); if (comparison.reveal.summary) reveal.append(el('p', '', comparison.reveal.summary)); if (comparison.reveal.details?.length) { const list = el('ul'); comparison.reveal.details.forEach(text => list.append(el('li', '', text))); reveal.append(list); } node.append(reveal); } }
    if (brief.chart?.items?.length) { const chart = brief.chart, figure = el('figure', 'brief-chart'); figure.append(el('figcaption', '', chart.label || chart.title || 'Recorded measurements')); const maximum = Math.max(1, ...chart.items.map(item => Number(item.value) || 0)); chart.items.forEach(item => { const row = el('div', 'chart-row'), labels = el('div', 'chart-label'), hasTotal = item.total !== undefined && item.total !== null, value = item.display_value ?? (hasTotal ? `${item.value} / ${item.total}` : String(item.value)); labels.append(el('span', '', item.label), el('strong', '', [value, chart.unit].filter(Boolean).join(' '))); const track = el('div', 'chart-track'), fill = el('span'), denominator = hasTotal ? Number(item.total) : maximum; fill.style.width = `${Math.max(0, Math.min(100, denominator > 0 ? Number(item.value) / denominator * 100 : 0))}%`; track.setAttribute('aria-hidden', 'true'); track.append(fill); row.append(labels, track); figure.append(row); }); if (chart.caveat) figure.append(el('p', 'small', chart.caveat)); node.append(figure); }
    if (Array.isArray(brief.what_is_not_proven) && brief.what_is_not_proven.length) { const list = el('ul'); brief.what_is_not_proven.forEach(text => list.append(el('li', '', text))); node.append(el('h3', '', 'What still needs evidence'), list); }
    if (brief.recommended_next) { const next = el('div', 'recommended'); next.append(el('h3', '', 'Suggested next step'), el('p', '', brief.recommended_next)); node.append(next); }
    const action = brief.human_action; if (action) { node.append(el('h2', '', action.kind === 'decision' ? 'Your decision' : 'Try it yourself')); if (action.title) node.append(el('p', '', action.title)); if (action.steps?.length) { const steps = el('ol'); action.steps.forEach(step => steps.append(el('li', '', step))); node.append(steps); } if (action.look_for) node.append(el('p', '', action.look_for)); if (withFeedback) feedback(node, brief.title, action); }
    if (brief.agent_action?.text) appendParagraph(node, 'What an agent can do', brief.agent_action.text); if (brief.agent_action?.reason) node.append(el('p', 'small', brief.agent_action.reason));
    if (brief.resources?.length) { node.append(el('h3', '', 'Project files and links'), artifactsView(brief.resources.map(r => ({ ...r, name: r.download || r.label, url: r.href, status: 'available', provenance: r.description || 'Resource selected for this summary.' })), 'Summary resource')); }
    node.append(briefFreshness(brief)); const details = el('details', 'source-details'); details.append(el('summary', '', 'Goal and summary provenance')); if (brief.user_goal?.text) details.append(el('p', '', brief.user_goal.text)); if (brief.user_goal?.confidence) details.append(el('p', '', `Goal source: ${brief.user_goal.confidence}`)); (brief.source_refs || []).forEach(ref => { details.append(el('p', '', [ref.note, ref.date].filter(Boolean).join(' · '))); if (ref.path) details.append(externalLink(ref.path, ref.path, '') || el('p', '', ref.path)); }); if (brief.source_update_id) details.append(routeLink('Read the source update', 'update', brief.source_update_id)); node.append(details); return node;
  }
  function taskRow(task) {
    const node = el('article', 'task-row'), heading = el('h3'); heading.append(routeLink(task.title, 'task', task.task_id, '', '')); node.append(heading); const pills = el('div', 'status-pills'); pills.append(workPill(task.work_state), executePill(task.execution_state)); node.append(pills, el('p', '', task.next_action || 'No next action recorded.'), el('p', 'small', `Work evidence ${time(task.source_time, true)} · Agent check ${time(task.activity_observed_at, true)}`)); const links = el('div', 'link-row'), thread = task.thread_id || task.chat_url?.match(/threads\/([^/?#]+)/)?.[1]; if (thread && sourceFor(thread)) links.append(routeLink('Read full chat updates', 'activity', '', thread)); const chat = externalLink('Open source chat', task.chat_url); if (chat) links.append(chat); const linear = externalLink('Open work record', task.linear_url); if (linear) links.append(linear); node.append(links); return node;
  }
  function projectView(id) {
    const group = [...(snapshot.projects.active || []), ...(snapshot.projects.all_projects || []), ...(snapshot.projects.history || [])].find(g => String(g.id) === id); if (!group) return empty('Project not found in this snapshot', 'Refresh for the latest project list, or return to Projects.');
    $('#pageTitle').textContent = group.name; $('#pageDescription').textContent = group.status || 'Project summary and original updates.'; const node = el('div'); node.append(routeLink('← All projects', 'projects', '', '', 'back-link'));
    const briefs = snapshot.briefs.briefs.filter(b => group.tasks.some(t => b.task_id === t.task_id || b.thread_id === t.thread_id)); briefs.forEach(b => node.append(briefView(b))); if (!briefs.length) node.append(empty('No coordinator summary saved yet', 'The recorded task handoffs and original chat updates below remain available.'));
    const heading = el('div', 'section-intro'); heading.append(el('h2', '', 'Task handoffs'), el('p', '', 'Work status and agent execution are recorded separately.')); node.append(heading); group.tasks.forEach(t => node.append(taskRow(t)));
    const ids = new Set(group.tasks.map(t => t.thread_id || t.chat_url?.match(/threads\/([^/?#]+)/)?.[1]).filter(Boolean)); const updates = snapshot.feed.updates.filter(u => ids.has(u.thread_id)); const intro = el('div', 'section-intro'); intro.append(el('h2', '', 'Original chat updates'), el('p', '', 'Full visible assistant wording. These messages are the source, rather than a rewritten summary.')); node.append(intro, updateList(updates)); return node;
  }
  function taskView(id) { const task = snapshot.projects.tasks.find(t => String(t.task_id) === id); if (!task) return empty('Task not found', 'Return to Projects or refresh the snapshot.'); $('#pageTitle').textContent = task.title; $('#pageDescription').textContent = task.project_name; const node = el('div'); node.append(routeLink('← All projects', 'projects', '', '', 'back-link')); const brief = briefFor(task); if (brief) node.append(briefView(brief)); node.append(taskRow(task)); const details = el('details', 'source-details'); details.append(el('summary', '', 'Evidence and recorded dates')); for (const [label, value] of [['Source', task.source], ['Deadline', task.deadline ? time(task.deadline, true) : ''], ['Completion evidence', task.completion_evidence]]) if (value) details.append(el('p', '', `${label}: ${typeof value === 'object' ? JSON.stringify(value) : value}`)); node.append(details); if (!brief) feedback(node, task.title); return node; }
  function decisionsView() { const node = el('div', 'decision-list'); const briefs = snapshot.briefs.briefs.filter(b => b.human_action && snapshot.projects.tasks.some(t => !PAST.has(t.work_state) && projectMatches(t.project_name) && (b.task_id ? b.task_id === t.task_id : (b.thread_id || b.source_id) === taskThread(t))) && matches([b.title, b.bottomline, b.human_action.title].join(' '))); briefs.forEach(b => { const heading = el('h2', '', b.title); const wrap = el('section'); wrap.append(heading, briefView(b)); node.append(wrap); }); snapshot.projects.tasks.filter(t => t.work_state === 'review' && !briefs.some(b => b.task_id === t.task_id) && projectMatches(t.project_name) && matches([t.title, t.next_action].join(' '))).forEach(t => node.append(taskRow(t))); if (!node.childNodes.length) node.append(empty('No recorded decisions in this view', 'Try another project or clear your search. New saved messages do not create decisions automatically.')); return node; }
  function sortedUpdates(items) { return [...items].sort((a, b) => score(messageTime(b)) - score(messageTime(a)) || (b.message_sequence || 0) - (a.message_sequence || 0)); }
  function updateList(items) {
    const node = el('div'); const filtered = sortedUpdates(items).filter(u => projectMatches(u.project_name || sourceFor(u.thread_id)?.project_name) && matches([u.title, u.project_name, u.text].join(' '))); if (!filtered.length) return empty('No saved messages match', 'Try another project or clear your search. Source coverage can be limited; the original chat may contain earlier messages.');
    const list = el('div', 'update-list'); filtered.slice(0, displayLimit).forEach(u => { const source = sourceFor(u.thread_id) || u, row = el('article', 'update-summary'), copy = el('div'), heading = el('h2'), meta = el('div', 'update-meta'); heading.append(routeLink(source.title || u.title || 'Project update', 'update', u.id, '', '')); meta.append(el('span', '', source.project_name || 'Project'), el('span', '', u.phase === 'final_answer' ? 'Final response' : 'Progress message')); const raw = String(u.text || 'No message text saved.'); copy.append(meta, heading, el('p', 'preview-text', raw.length > 250 ? raw.slice(0, 250) + '…' : raw)); const links = el('div', 'link-row'); links.append(routeLink('Read the complete update', 'update', u.id)); if (u.completeness !== 'complete') links.append(pill(u.completeness === 'streaming' ? 'Saved so far' : 'Incomplete capture', 'warning')); copy.append(links); const timestamp = el('time', '', time(messageTime(u), true)); if (messageTime(u)) timestamp.dateTime = messageTime(u); row.append(el('span', 'timeline-mark'), copy, timestamp); list.append(row); }); node.append(list);
    const pager = el('div', 'pagination'); pager.append(el('span', '', `${Math.min(displayLimit, filtered.length)} of ${filtered.length} saved messages`)); if (displayLimit < filtered.length) pager.append(button('Show more', () => { displayLimit += 12; render({ keepAssets: true }); })); node.append(pager); return node;
  }
  function sourcesView(ids) { const section = el('section'); section.append(el('h2', '', 'Source checks and archive coverage')); const list = el('div', 'source-list'); snapshot.feed.sources.filter(s => !ids || ids.has(s.thread_id)).forEach(s => { const check = snapshot.sync?.sources?.find(row => row.thread_id === s.thread_id), row = el('div', 'source-row'); row.append(el('strong', '', s.title || 'Source chat'), el('p', '', `${s.project_name || 'Project'} · Checked ${time(check?.last_success_at || s.last_checked_at, true)} · ${s.update_count ?? snapshot.feed.updates.filter(u => u.thread_id === s.thread_id).length} saved messages`), el('p', '', s.history_note || (s.history_complete ? 'Source archive is recorded as complete.' : 'Earlier history may be missing.'))); if (check?.availability === 'unavailable') row.append(el('p', 'capture-note', 'This source could not be checked. Earlier saved messages remain available.')); row.append(routeLink('Read saved messages', 'history', '', s.thread_id)); list.append(row); }); section.append(list); return section; }
  function activityView(thread) { const node = el('div'), cutoff = Date.now() - 7 * 86400000; if (thread) { const source = sourceFor(thread); $('#pageTitle').textContent = source?.title || 'Saved chat updates'; $('#pageDescription').textContent = 'All saved messages from this source, with full original wording.'; node.append(routeLink('← Recent activity', 'activity', '', '', 'back-link')); } const updates = snapshot.feed.updates.filter(u => thread ? u.thread_id === thread : score(messageTime(u)) >= cutoff); node.append(updateList(updates)); const heading = el('div', 'section-intro'); heading.append(el('h2', '', 'About these updates'), el('p', '', 'The reader captures assistant commentary and final responses. Tool calls, reasoning and user messages are outside this archive. A completed turn does not establish that the project is finished.')); node.append(heading, sourcesView(thread ? new Set([thread]) : null)); return node; }
  function historyView(thread) { const node = el('div'); if (!thread) { const past = snapshot.projects.tasks.filter(t => PAST.has(t.work_state) && projectMatches(t.project_name) && matches([t.title, t.project_name, t.next_action].join(' '))); if (past.length) { const intro = el('div', 'section-intro'); intro.append(el('h2', '', 'Completed and paused work')); node.append(intro); past.forEach(t => node.append(taskRow(t))); } const heading = el('div', 'section-intro'); heading.append(el('h2', '', 'All saved messages'), el('p', '', 'Recent updates appear here too. Older messages remain available without turning them into current work.')); node.append(heading); } else { const source = sourceFor(thread); $('#pageTitle').textContent = source?.title || 'Source history'; $('#pageDescription').textContent = 'All messages captured for this source. Archive coverage is shown below.'; node.append(routeLink('← History', 'history', '', '', 'back-link')); } node.append(updateList(snapshot.feed.updates.filter(u => !thread || u.thread_id === thread)), el('div', 'section-intro'), sourcesView(thread ? new Set([thread]) : null)); return node; }
  async function assetBlob(path, expectedGeneration = generation) { const blob = await request(path, true); if (expectedGeneration !== generation) throw new Error('view_changed'); const url = URL.createObjectURL(blob); objectUrls.add(url); return { url, blob }; }
  function openImage(url, name, context, trigger) { imageTrigger = trigger || document.activeElement; $('#viewerImage').src = url; $('#viewerImage').alt = name || 'Project image'; $('#imageTitle').textContent = name || 'Project image'; $('#imageContext').textContent = context || 'Authenticated project artifact'; $('#imageViewer').showModal(); }
  function assetButton(artifact, context) { const path = artifactPath(artifact.url), text = artifact.label || artifact.name || 'Project artifact'; if (artifact.status === 'unavailable') return el('span', 'asset-unavailable', `${text}: ${artifact.reason || 'unavailable on this connection'}`); if (!path) { const external = externalLink(text, artifact.url, 'button'); return external || el('span', 'asset-unavailable', `${text}: ${artifact.reason || 'unavailable on this connection'}`); } const status = el('span', 'small'), node = button(text, async () => { node.disabled = true; const expected = generation; try { const { url, blob } = await assetBlob(path, expected); if (/^image\/(png|jpeg|webp|gif|avif)$/.test(blob.type)) openImage(url, text, context, node); else { const download = el('a'); download.href = url; download.download = safeName(artifact.download || artifact.name || text); download.style.display = 'none'; document.body.append(download); download.click(); download.remove(); } status.textContent = ''; } catch { status.textContent = 'File unavailable. Reconnect to the laptop, then try again.'; } finally { node.disabled = false; } }); const wrap = el('div'); wrap.append(node, status); return wrap; }
  function artifactsView(items, context) { const list = el('div', 'artifact-list'); items.forEach(artifact => { const item = el('div', 'artifact'); item.append(assetButton(artifact, context)); if (artifact.provenance || artifact.description) item.append(el('p', '', artifact.provenance || artifact.description)); if (artifact.original_path) { const details = el('details', 'source-details'); details.append(el('summary', '', 'Original file provenance · laptop only'), externalLink(artifact.original_path, artifact.original_path, '') || el('p', '', artifact.original_path)); item.append(details); } list.append(item); }); return list; }
  function sanitizedBody(update) {
    const body = el('div', 'update-body'); if (!update.body_html) { body.append(el('pre', 'plain-text', update.text || 'No message text saved.')); return body; }
    const template = document.createElement('template'); template.innerHTML = String(update.body_html);
    const allowed = new Set(['P', 'BR', 'STRONG', 'B', 'EM', 'I', 'S', 'DEL', 'UL', 'OL', 'LI', 'H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'PRE', 'CODE', 'BLOCKQUOTE', 'HR', 'TABLE', 'THEAD', 'TBODY', 'TR', 'TD', 'TH', 'A', 'IMG', 'FIGURE', 'FIGCAPTION', 'SPAN', 'DIV', 'DETAILS', 'SUMMARY']);
    const discard = new Set(['SCRIPT', 'STYLE', 'IFRAME', 'OBJECT', 'EMBED', 'SVG', 'MATH', 'LINK', 'META', 'FORM', 'INPUT', 'BUTTON', 'TEXTAREA', 'SELECT', 'AUDIO', 'VIDEO', 'SOURCE']);
    const clean = node => {
      if (node.nodeType === Node.TEXT_NODE) return document.createTextNode(node.textContent);
      if (node.nodeType !== Node.ELEMENT_NODE) return null;
      if (discard.has(node.tagName)) return null;
      if (!allowed.has(node.tagName)) { const fragment = document.createDocumentFragment(); for (const child of node.childNodes) { const next = clean(child); if (next) fragment.append(next); } return fragment; }
      if (node.tagName === 'IMG') {
        const path = artifactPath(node.getAttribute('src')), label = node.getAttribute('alt') || 'Image from this update'; if (!path) return el('span', 'asset-unavailable', `${label}: image unavailable on this connection`);
        const wrap = el('figure'), image = el('img'), trigger = button('', () => { if (image.src.startsWith('blob:')) openImage(image.src, label, sourceFor(update.thread_id)?.title || update.title, trigger); }, 'image-button'); image.alt = label; image.loading = 'lazy'; trigger.setAttribute('aria-label', `Enlarge image: ${label}`); trigger.append(image); wrap.append(trigger, el('figcaption', '', label)); const expected = generation; assetBlob(path, expected).then(({ url, blob }) => { if (expected !== generation || !/^image\/(png|jpeg|webp|gif|avif)$/.test(blob.type)) return; image.src = url; }).catch(() => { if (expected === generation) wrap.replaceChildren(el('span', 'asset-unavailable', `${label}: could not be loaded. Reconnect to the laptop to try again.`)); }); return wrap;
      }
      if (node.tagName === 'A') { const href = node.getAttribute('href') || '', path = artifactPath(href); if (path) return assetButton({ url: path, name: node.getAttribute('download') || node.textContent || 'Project file', label: node.textContent || 'Project file', download: node.getAttribute('download') || undefined, status: 'available' }, 'Artifact linked in original update'); const link = externalLink(node.textContent, href, ''); if (link) return link; const span = el('span', '', node.textContent); return span; }
      const safe = el(node.tagName.toLowerCase()); if (['TD', 'TH'].includes(node.tagName)) for (const key of ['colspan', 'rowspan']) { const value = Number(node.getAttribute(key)); if (Number.isInteger(value) && value > 0 && value <= 30) safe.setAttribute(key, String(value)); } if (node.tagName === 'OL') { const start = Number(node.getAttribute('start')); if (Number.isInteger(start) && start > 0 && start < 10000) safe.setAttribute('start', String(start)); }
      for (const child of node.childNodes) { const next = clean(child); if (next) safe.append(next); } if (node.tagName === 'PRE' || node.tagName === 'TABLE') { safe.tabIndex = 0; safe.setAttribute('aria-label', node.tagName === 'TABLE' ? 'Scrollable source table' : 'Scrollable code block'); } return safe;
    };
    for (const child of template.content.childNodes) { const safe = clean(child); if (safe) body.append(safe); } return body;
  }
  function messageView(update) {
    const node = el('article', 'message'); node.id = `message-${update.id}`; const meta = el('header', 'message-meta'), timestamp = el('time', '', `${update.message_created_at || update.message_completed_at ? '' : 'Saved '}${time(messageTime(update), true)}`); if (messageTime(update)) timestamp.dateTime = messageTime(update); meta.append(el('strong', '', update.phase === 'final_answer' ? 'Final response' : 'Progress message'), timestamp); node.append(meta); if (update.completeness !== 'complete') node.append(el('p', 'capture-note', update.completeness === 'streaming' ? 'Saved so far. This message may still be growing; refresh to check for more text.' : 'This capture is incomplete. Open the source chat for the rest of the message.')); node.append(sanitizedBody(update));
    const original = el('pre', 'original-text', update.text || ''); original.hidden = true; original.tabIndex = 0; original.id = `original-${update.id}`; original.setAttribute('aria-label', 'Original message text'); const toggle = button('Original text', () => { original.hidden = !original.hidden; toggle.textContent = original.hidden ? 'Original text' : 'Hide original text'; toggle.setAttribute('aria-expanded', String(!original.hidden)); }, 'button subtle'); toggle.setAttribute('aria-expanded', 'false'); toggle.setAttribute('aria-controls', original.id); const status = el('p', 'copy-status'); status.setAttribute('role', 'status'); const actions = el('div', 'message-actions'); actions.append(toggle, button('Copy text', async () => { try { await navigator.clipboard.writeText(update.text || ''); status.textContent = 'Original text copied.'; } catch { original.hidden = false; toggle.textContent = 'Hide original text'; toggle.setAttribute('aria-expanded', 'true'); const range = document.createRange(); range.selectNodeContents(original); window.getSelection().removeAllRanges(); window.getSelection().addRange(range); original.focus(); status.textContent = 'Text selected. Use your copy shortcut.'; } }, 'button subtle'), routeLink('Link to this message', 'update', update.id)); node.append(actions, original, status);
    if (update.artifacts?.length) node.append(artifactsView(update.artifacts, 'Artifact linked in original update'));
    const source = el('details', 'source-details'); source.append(el('summary', '', 'Message provenance and completeness')); const facts = el('dl'); for (const [label, value] of [['Source chat', sourceFor(update.thread_id)?.title || update.title], ['Source message ID', update.message_id], ['Source turn ID', update.turn_id], ['Capture', update.completeness || 'Unknown'], ['First observed', time(update.first_observed_at, true)], ['Last observed', time(update.last_observed_at, true)], ['Revision', update.revision_count], ['Original project location', update.cwd]]) if (value !== undefined && value !== null) { const detail = el('dd'); detail.append(label === 'Original project location' ? externalLink(value, value, '') || document.createTextNode(String(value)) : document.createTextNode(String(value))); facts.append(el('dt', '', label), detail); } source.append(facts); node.append(source); return node;
  }
  function updateView(id) {
    const selected = snapshot.feed.updates.find(u => u.id === id); if (!selected) return empty('Saved update not found', 'The current archive does not contain this message. Refresh or open its source chat.'); const source = sourceFor(selected.thread_id) || selected, group = snapshot.feed.updates.filter(u => u.thread_id === selected.thread_id && (selected.turn_id ? u.turn_id === selected.turn_id : u.id === id)).sort((a, b) => Number.isFinite(a.message_sequence) && Number.isFinite(b.message_sequence) ? a.message_sequence - b.message_sequence : score(messageTime(a)) - score(messageTime(b)));
    $('#pageTitle').textContent = source.title || 'Complete update'; $('#pageDescription').textContent = `${source.project_name || 'Project'} · Original visible assistant updates`; const node = el('div', 'reading-page'); node.append(routeLink('← Saved chat updates', 'activity', '', selected.thread_id, 'back-link')); const head = el('div', 'turn-heading'); head.append(el('h2', '', `${group.length} saved ${group.length === 1 ? 'message' : 'messages'} in this turn`), el('p', '', source.history_note || 'Archive coverage is not recorded. Earlier source messages may be missing.')); const sourceLink = externalLink('Open source chat in Codex', selected.source_url || source.source_url); if (sourceLink) head.append(sourceLink, el('p', 'small', 'Source chats open in the Codex desktop app. On a phone, read the saved messages here or copy the chat link for your laptop.')); node.append(head); group.forEach(u => { const message = messageView(u); if (u.id === id) { message.classList.add('selected'); message.setAttribute('aria-current', 'true'); } node.append(message); }); if (source.artifacts?.length) { node.append(el('h2', '', 'Related project artifacts'), el('p', 'small', 'These artifacts were selected for the source separately. They are not attachments inferred from this turn.'), artifactsView(source.artifacts, 'Related project artifact selected for source')); } const list = sortedUpdates(snapshot.feed.updates.filter(u => u.thread_id === selected.thread_id)); const at = list.findIndex(u => u.id === id), pager = el('nav', 'pagination'); pager.setAttribute('aria-label', 'Adjacent saved messages'); if (list[at + 1]) pager.append(routeLink('← Earlier message', 'update', list[at + 1].id)); if (list[at - 1]) pager.append(routeLink('Newer message →', 'update', list[at - 1].id)); node.append(pager, sourcesView(new Set([selected.thread_id]))); return node;
  }
  function render({ keepAssets = false } = {}) {
    if (!keepAssets) revokeAssets(); renderConnection(); renderNotice(); const current = route(), mainView = current.view === 'project' || current.view === 'task' ? 'projects' : current.view === 'update' ? 'activity' : current.view; document.querySelectorAll('[data-view]').forEach(node => { if (node.dataset.view === mainView) node.setAttribute('aria-current', 'page'); else node.removeAttribute('aria-current'); }); const [title, desc] = views[mainView]; $('#pageTitle').textContent = title; $('#pageDescription').textContent = desc; $('#filters').hidden = !snapshot || ['project', 'update', 'task'].includes(current.view); $('#snapshotTime').hidden = !snapshot; $('#snapshotTime').textContent = snapshot ? `Fetched ${time(lastFetched)}` : ''; const host = $('#content');
    if (!snapshot) { const loading = el('div', 'loading'); loading.setAttribute('role', 'status'); loading.setAttribute('aria-label', 'Loading private project data'); for (let i = 0; i < 3; i++) loading.append(el('div', 'skeleton')); host.replaceChildren(connection === 'loading' ? loading : welcome()); $('#decisionCount').hidden = true; $('#footerStatus').textContent = 'Private data loads after pairing.'; return; }
    const selected = $('#projectFilter').value; const names = [...new Set(snapshot.projects.tasks.map(t => t.project_name).concat((snapshot.projects.all_projects || []).map(p => p.name)))].sort(); $('#projectFilter').replaceChildren(el('option', '', 'All projects')); $('#projectFilter').firstChild.value = ''; names.forEach(name => { const option = el('option', '', name); option.value = name; $('#projectFilter').append(option); }); $('#projectFilter').value = selected;
    const decisions = snapshot.projects.tasks.filter(t => t.work_state === 'review').length; $('#decisionCount').hidden = !decisions; $('#decisionCount').textContent = decisions; $('#footerStatus').textContent = `Reader fetch ${time(lastFetched, true)}. Work evidence has its own dates.`;
    let content; if (current.view === 'project') content = projectView(current.id); else if (current.view === 'task') content = taskView(current.id); else if (current.view === 'update') content = updateView(current.id); else if (current.view === 'activity') content = activityView(current.thread); else if (current.view === 'decisions') content = decisionsView(); else if (current.view === 'history') content = historyView(current.thread); else content = projectsView(); host.replaceChildren(content);
  }
  $('#pairForm').addEventListener('submit', connect); $('#connectionButton').addEventListener('click', () => $('#connectionPanel').hidden ? openConnection() : $('#connectionPanel').hidden = true); $('#closeConnection').addEventListener('click', () => { $('#connectionPanel').hidden = true; $('#connectionButton').focus(); }); $('#forgetButton').addEventListener('click', forget); $('#showKey').addEventListener('click', () => { const shown = $('#pairingKey').type === 'text'; $('#pairingKey').type = shown ? 'password' : 'text'; $('#showKey').textContent = shown ? 'Show' : 'Hide'; $('#showKey').setAttribute('aria-pressed', String(!shown)); }); $('#rememberTab').addEventListener('change', savePairing); $('#refreshButton').addEventListener('click', () => load()); $('#search').addEventListener('input', () => { clearTimeout(searchTimer); searchTimer = setTimeout(() => { displayLimit = 12; render(); }, 160); }); $('#projectFilter').addEventListener('change', () => { displayLimit = 12; render(); });
  $('.skip-link').addEventListener('click', event => { event.preventDefault(); $('#main').focus(); $('#main').scrollIntoView({ block: 'start' }); });
  $('#closeImage').addEventListener('click', () => $('#imageViewer').close()); $('#imageViewer').addEventListener('close', () => { $('#viewerImage').removeAttribute('src'); if (imageTrigger?.isConnected) imageTrigger.focus(); }); $('#imageViewer').addEventListener('click', event => { if (event.target === $('#imageViewer')) { const rect = $('#imageViewer').getBoundingClientRect(); if (event.clientX < rect.left || event.clientX > rect.right || event.clientY < rect.top || event.clientY > rect.bottom) $('#imageViewer').close(); } });
  function focusRoute() { const current = route(), message = current.view === 'update' ? document.getElementById(`message-${current.id}`) : null; if (message) { message.tabIndex = -1; message.focus({ preventScroll: true }); message.scrollIntoView({ block: 'start' }); } else { window.scrollTo(0, 0); $('#pageTitle').tabIndex = -1; $('#pageTitle').focus({ preventScroll: true }); } }
  window.addEventListener('hashchange', () => { displayLimit = 12; $('#search').value = ''; $('#projectFilter').value = ''; render(); focusRoute(); }); window.addEventListener('online', () => { if (pairing) load(); }); window.addEventListener('pagehide', () => { controllers.forEach(c => c.abort()); });
  function canAutoRefresh() { return pairing && document.visibilityState === 'visible' && !['update', 'project', 'task', 'decisions'].includes(route().view) && $('#connectionPanel').hidden && !['INPUT', 'TEXTAREA', 'SELECT'].includes(document.activeElement?.tagName); }
  document.addEventListener('visibilitychange', () => { if (canAutoRefresh() && Date.now() - score(lastFetched) > 60000) load(); });
  remember(); render(); discover().then(() => { if (pairing) load(); }); refreshTimer = setInterval(() => { if (canAutoRefresh()) load(); }, 60000);
})();
